name: Terraform Check
on:
  workflow_call:
    inputs:
      use_environment:
        required: false
        type: string
        default: "false"
      environment:
        required: false
        type: string
      terraform_workspace_path:
        required: true
        type: string
      var_file:
        required: true
        type: string
      backend_key:
        required: true
        type: string  # Only the key is passed, NOT the full backend_config string
    secrets:
      BACKEND_CONFIG:
        required: true
      ARM_SUBSCRIPTION_ID:
        required: true
      ARM_CLIENT_ID:
        required: true
      ARM_TENANT_ID:
        required: true

jobs:
  terraform-check:
    runs-on: ubuntu-latest
    environment: ${{ inputs.use_environment == 'true' && inputs.environment || '' }}
    env:
        ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
        ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
        ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Terraform Check
        id: check
        uses: dflook/terraform-check@v1
        with:
          path: ${{ inputs.terraform_workspace_path }}
          var_file: ${{ inputs.var_file }}
          backend_config: "key=${{ inputs.backend_key }},${{ secrets.BACKEND_CONFIG }}"
      - name: Changes detected
        if: ${{ failure() && steps.check.outputs.failure-reason == 'changes-to-apply' }}
        run: echo ':x: Drift has been detected in your terraform configuration' >> $GITHUB_STEP_SUMMARY      
