name: Terraform Plan
on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
      terraform_workspace_path:
        required: true
        type: string
      var_file:
        required: true
        type: string
      backend_key:
        required: true
        type: string  # Only the key is passed, NOT the full backend_config string
    secrets:
      BACKEND_CONFIG:
        required: true
      ARM_SUBSCRIPTION_ID:
        required: true
      ARM_CLIENT_ID:
        required: true
      ARM_TENANT_ID:
        required: true

jobs:
  plan:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    env:
        ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
        ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
        ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
    steps:
      - name: Checkout Repository 
        uses: actions/checkout@v4
      - name: Terraform Plan
        uses: dflook/terraform-plan@v1.46.1
        with:
          add_github_comment: changes-only
          path: ${{ inputs.terraform_workspace_path }}
          var_file: ${{ inputs.var_file }}
          backend_config: "key=${{ inputs.backend_key }},${{ secrets.BACKEND_CONFIG }}"
